name: doc_helin
description: "Doctor helin Patint managment system"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2
  http: ^1.3.0
  shared_preferences: ^2.5.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  cupertino_calendar_picker: ^2.1.7
  intl: ^0.19.0
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/purple-bg.jpg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          style: normal
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
